####################
# Initial ##########
####################

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'hecal3/vim-leader-guide'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

####################
# Completion #######
####################

[[plugins]]
repo = 'Shougo/deoplete.nvim'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'

####################
# Scala ############
####################

[[plugins]]
repo = 'ensime/ensime-vim'
on_ft = ['scala']

#[[plugins]]
#repo = 'dragos/dragos-vscode-scala'

#[[plugins]]
#repo = 'derekwyatt/vim-scala'

####################
# Python ###########
####################

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'

